#!/bin/bash

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# prepend our script_dir onto PYTHONPATH (use ';' only if PYTHONPATH is non-empty)
export PYTHONPATH="$script_dir${PYTHONPATH:+;$PYTHONPATH}"

# Check OS and activate virtual environment accordingly
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" || "$OSTYPE" == "win32" ]]; then
    # On Windows (Git Bash, MSYS2, Cygwin)
    source "$script_dir/.venv/Scripts/activate"
else
    # On Unix-like systems (Linux, macOS)
    source "$script_dir/.venv/bin/activate"
fi

python "$@"

deactivate